### ISSUE TITLE
The Digital Clock App disappeared.

### ISSUE THREAD

**Issue by CodingSpecies** [Programmer005/screen-recorder#3]
@Programmer005 , I forked and made changes to your digital clock app, and when I saw, my forked version, and your version has disappeared. I don't know if it was removed. Thank you.

**Comment by Programmer005** [comment]
Sorry, Your changes were good but I deleted it by mistake. I have the original copy in my PC, I will make a new one. Sorry for the inconvenience

**Comment by CodingSpecies** [comment]
It's ok, thank you! 👍🏼 :)
